---
title: "Week 13"
subtitle: "Peer Review & Shiny apps"
output: 
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Thursday Announcements

-   Due tonight: Stats experience points + Lab 09

    -   If you submitted Lab 09 prior to class-time on Tuesday, please re-submit (sorry!)

-   Will accept extra credit Stats Experience points through Sat 12/10 (same day written report is due)

-   End of Course reflection (1/2 page to 1 page) - due Thurs 12/15 (same day as presentations)

-   Fill out IDEA Course Evaluation. \>80% participation will earn everyone 3 extra credit points on final project - due Fri 12/9 (APU deadline)

### Thursday - Shiny Part I

-   For AE-11, you will complete Lessons 03 - 05 from the [Shiny Getting Started Tutorials](https://shiny.rstudio.com/tutorial/written-tutorial/lesson3/)

-   These should be completed in your Shiny project in the `MATH_250_individual` workspace

-   You will turn in a .zip folder that includes the `lesson-03` and `census-app` folders as well as the .Rproj file from your Shiny project

### Tuesday Announcements

End-of-semester schedule:

+--------------+-------------------------+----------------------+----------------------------------+
|              | Tuesday                 | Thursday             | What's due                       |
+==============+=========================+======================+==================================+
| Week 13      | Rough draft peer review | Shiny part I         | Shiny prep (Th)                  |
|              |                         |                      |                                  |
|              |                         |                      | Lab 09 (Th)                      |
|              |                         |                      |                                  |
|              |                         |                      | SE 02 (Th)                       |
|              |                         |                      |                                  |
|              |                         |                      | AE-11 (Sat)                      |
+--------------+-------------------------+----------------------+----------------------------------+
| Week 14      | Shiny part II           | Project work session | Shiny prep II (Tue)              |
|              |                         |                      |                                  |
|              |                         |                      | Formal peer review (Tue)         |
|              |                         |                      |                                  |
|              |                         |                      | AE-12 (Th)                       |
|              |                         |                      |                                  |
|              |                         |                      | Final report (Sat)               |
+--------------+-------------------------+----------------------+----------------------------------+
| Week 15      |                         | Final presentations  | End-of-course reflection (Thurs) |
|              |                         |                      |                                  |
|              |                         | (on-campus)          |                                  |
+--------------+-------------------------+----------------------+----------------------------------+

### Questions?

### Rough Draft Peer Review

Why peer review?

-   Giving good feedback is a skill (that we don't often practice)

-   Receiving and incorporating feedback effectively also takes practice

-   Our work is better when we have multiple perspectives speak into it

-   Makes us better at self-assessing our own work

-   It's part of the scientific process

We will do the following twice:

-   (10 mins) In your project groups, discuss assigned paper and fill out feedback form in the shared [Google Drive folder](https://drive.google.com/drive/folders/190TgJca5qleOGoQQMJ6IbLj_RbSRKtOE?usp=share_link) ("Peer feedback for Group X")

-   (15 mins) Pair up with the group and exchange feedback (\~7 mins per group)

+-------------+--------------------+
|             | Group pairings     |
+=============+====================+
| Session 1   | Group 1 & Group 3  |
|             |                    |
|             | Group 4 & Group 6  |
|             |                    |
|             | Group 2 & Dr. Fitz |
+-------------+--------------------+
| Session 2   | Group 1 & Group 6  |
|             |                    |
|             | Group 2 & Group 4  |
|             |                    |
|             | Group 3 & Dr. Fitz |
+-------------+--------------------+

### General Tips

-   Hide code in final report (can have code chunk with `knitr::opts_chunk$set(echo = FALSE)` at the top of your .Rmd)

-   Think about audience:

    -   Generally educated stakeholder - not necessarily an analyst

    -   The .Rmd can have thorough commenting for an analyst to follow, but don't need to include all the analysis/coding decisions in the report itself

    -   Avoid heavy jargon (both statistical and R-related)

-   Focus more on commentary of your results and what they mean, less on analysis/coding decisions

-   Use spellcheck :)

-   Use "English" in your table headers - rather than the raw column headers

### 
